# Generated by Django 5.1.6 on 2025-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("num_phone", models.CharField(max_length=20)),
                ("sex", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("birth_date", models.DateField()),
            ],
        ),
    ]
