# Generated by Django 5.2.1 on 2025-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("num_phone", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("sex", models.CharField(max_length=10)),
                ("birth_date", models.DateField()),
            ],
        ),
    ]
