# Generated by Django 5.2.1 on 2025-05-14 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                ("med_rec_id", models.AutoField(primary_key=True, serialize=False)),
                ("diagnosis", models.TextField()),
                ("medical_analysis", models.TextField()),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healytics.history",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalChat",
            fields=[
                ("chat_id", models.AutoField(primary_key=True, serialize=False)),
                ("chat_summary", models.TextField()),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healytics.medicalrecord",
                    ),
                ),
            ],
        ),
    ]
