# Generated by Django 5.2 on 2025-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_medical', '0002_rename_user_conversation_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='diagnosis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
